import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const vazirFont = localFont({
  src: "../public/fonts/Vazirmatn-Regular.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={vazirFont.className}>
        <nav className="w-full h-8 bg-slate-300 flex justify-between items-center px-2">
          <span className="">نام کاربر</span>
          <span className="">خروج</span>
        </nav>
        {children}
      </body>
    </html>
  );
}
